### create new task
POST http://localhost:8000/api/task
Content-Type: application/json

{
  "title": "Clean room",
  "description": "Clean my room today"
}

### get all tasks
GET http://localhost:8000/api/task

### get task by id
GET http://localhost:8000/api/task/2

### delete task
DELETE http://localhost:8000/api/task/2